version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    working_dir: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''